# Don't print a new line at the start of the prompt
add_newline = true

[character]
symbol = "âœï¸ ~>"
error_symbol = "ğŸ¬ ~"
vicmd_symbol = "[NORMAL]"
use_symbol_for_status = true

[package]
disabled = true

